#!/usr/bin/env python3
"""Run the one allowed class-agnostic AP for the frozen safety60 action plan.

The entry point first verifies the model digest, official100 five-fold result,
scene isolation, complete no-GT plan, and every frozen candidate-input digest.
It then materializes the selected candidate set only in memory and calls the
AP aggregator exactly once for ``structured_lower_relation_veto``.
"""
from __future__ import annotations

import argparse
import json
import os
import pickle
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from tools.audit_train_candidate_quality_dataset import candidate_ledger_path, read_jsonl, read_scene_list  # noqa: E402
from tools.build_safety60_structured_action_plan import POLICY, _combined_digest  # noqa: E402
from tools.build_train_candidate_component_action_utility_ledger import _sha256  # noqa: E402
from tools.diagnose_gvc_class_agnostic_ap import (  # noqa: E402
    _class_agnostic_gt_ids,
    _configure_scannet200_instance_eval,
    instance_eval,
)
from tools.evaluate_candidate_quality_reranking_class_agnostic_ap import (  # noqa: E402
    FEATURE_GROUP,
    PROTOCOL_NAME,
    _combined_file_digest,
    _evaluate,
    _load_track_points,
    _prediction,
    load_safety_scene,
)
from tools.evaluate_official100_geometry_group_ranking_oof_ap import (  # noqa: E402
    geometry_groups_and_audit,
)
from tools.train_candidate_quality_head_oof import canonicalize_predictions, feature_matrix  # noqa: E402


VERSION = "safety60_structured_lower_relation_veto_ap_v1"


def _resolve(path: Path) -> Path:
    return path if path.is_absolute() else PROJECT_ROOT / path


def _candidate_input_paths(scene: str, args) -> list[Path]:
    payload_path = args.track_root / scene / "automatic_tracks.json"
    tracks = json.loads(payload_path.read_text()).get("tracks", [])
    scene_stem = scene[5:] if scene.startswith("scene") else scene
    return [
        args.native_cache / f"{scene}_pred_masks.npy",
        args.native_cache / f"{scene}_pred_scores.npy",
        args.native_cache / f"{scene}_pred_classes.npy",
        payload_path,
        args.quality_ledger_root / scene / "c1_gvc_quality_ledger.json",
        args.dataset_root / scene / f"{scene_stem}.npy",
        *(Path(track["points_path"]) for track in tracks),
    ]


def preflight(args: argparse.Namespace) -> dict:
    scenes = read_scene_list(args.safety_scene_list)
    official_scenes = read_scene_list(args.official_scene_list)
    if len(scenes) != 60 or len(official_scenes) != 100:
        raise ValueError("frozen protocol requires official100 and safety60")
    overlap = sorted(set(scenes) & set(official_scenes))
    if overlap:
        raise ValueError(f"official100/safety60 scene overlap: {overlap}")

    plan_summary = json.loads((args.plan_root / "summary.json").read_text())
    required = {
        "policy": POLICY,
        "scene_count": 60,
        "official100_safety60_scene_overlap_count": 0,
        "feature_schema_verified": True,
        "plan_complete": True,
        "ground_truth_usage": "none",
        "candidate_files_modified": False,
        "candidate_file_modification_count": 0,
        "ap_evaluation_run": False,
        "ap_evaluation_run_count": 0,
        "threshold_scanning": False,
    }
    mismatches = {
        key: {"expected": value, "actual": plan_summary.get(key)}
        for key, value in required.items() if plan_summary.get(key) != value
    }
    if mismatches:
        raise ValueError(f"no-GT plan summary violates frozen contract: {mismatches}")

    model_metadata = json.loads((args.model_root / "metadata.json").read_text())
    package_path = args.model_root / "model_package.pkl"
    package_sha = _sha256(package_path)
    if package_sha != model_metadata["model_package_sha256"]:
        raise ValueError("model package SHA-256 mismatch")
    if plan_summary["input_provenance"]["model_package_sha256"] != package_sha:
        raise ValueError("plan was not generated by the supplied model package")
    if model_metadata["frozen_policy"] != POLICY or model_metadata["threshold_scanning"]:
        raise ValueError("model metadata does not freeze the selected policy")
    if model_metadata["fit_diagnostics"]["candidate_quality"]["q"]["random_seed"] != 20260808:
        raise ValueError("candidate quality q seed differs from frozen coexist baseline")

    official = json.loads(args.official_oof_summary.read_text())
    delta = official["policy_ap_delta_vs_coexist"][POLICY]
    if not all(float(delta[name]) > 0.0 for name in ("official_ap", "ap50", "ap25")):
        raise ValueError("official100 selected policy is not positive on all three metrics")
    fold_deltas = []
    for fold in official["fold_policy_ap"]["folds"]:
        metrics = fold["policy_global_metrics"]
        value = float(metrics[POLICY]["official_ap"] - metrics["always_coexist"]["official_ap"])
        fold_deltas.append(value)
    if len(fold_deltas) != 5 or not all(value > 0.0 for value in fold_deltas):
        raise ValueError(f"official100 main AP is not positive in every fold: {fold_deltas}")

    coexist_summary = json.loads(args.frozen_coexist_summary.read_text())
    coexist_contract = coexist_summary["模型合同"]
    if coexist_contract["random_seed"] != 20260808:
        raise ValueError("historical safety60 coexist baseline has unexpected q seed")
    ledger_paths = [candidate_ledger_path(args.official_records_root, scene) for scene in official_scenes]
    if _combined_file_digest(ledger_paths) != coexist_contract["training_ledgers_combined_sha256"]:
        raise ValueError("official candidate-quality training ledger digest differs from coexist baseline")

    aggregate_plan = read_jsonl(args.plan_root / "frozen_action_plan.jsonl")
    identities = {
        (str(row["scene_name"]), int(row["relation_component_id"])) for row in aggregate_plan
    }
    if len(identities) != len(aggregate_plan) or len(aggregate_plan) != plan_summary["relation_component_count"]:
        raise ValueError("aggregate plan identities are incomplete or duplicated")
    if {row["policy"] for row in aggregate_plan} != {POLICY}:
        raise ValueError("aggregate plan contains a non-frozen policy")

    observed_input_digests = {}
    for scene in scenes:
        scene_summary = json.loads((args.plan_root / scene / "summary.json").read_text())
        scene_plan = read_jsonl(args.plan_root / scene / "frozen_action_plan.jsonl")
        if len(scene_plan) != int(scene_summary["relation_component_count"]):
            raise ValueError(f"{scene}: scene plan does not cover all components")
        digest = _combined_digest(_candidate_input_paths(scene, args))
        expected = plan_summary["input_provenance"]["scene_candidate_input_sha256"][scene]
        if digest != expected or digest != scene_summary["candidate_input_combined_sha256"]:
            raise ValueError(f"{scene}: frozen candidate input digest mismatch")
        observed_input_digests[scene] = digest
    return {
        "preflight_passed": True,
        "scene_count": len(scenes),
        "official100_safety60_overlap_count": 0,
        "official100_policy_delta": delta,
        "official100_fold_main_ap_deltas": fold_deltas,
        "model_package_sha256": package_sha,
        "plan_summary_sha256": _sha256(args.plan_root / "summary.json"),
        "frozen_coexist_summary_sha256": _sha256(args.frozen_coexist_summary),
        "frozen_coexist_metrics": coexist_summary["AP结果"]["基线分组原始分数加轨迹质量分数"],
        "candidate_input_digest_count": len(observed_input_digests),
        "ground_truth_read": False,
        "ap_evaluation_run_count": 0,
    }


def run_once(args: argparse.Namespace, audit: dict) -> dict:
    scenes = read_scene_list(args.safety_scene_list)
    with (args.model_root / "model_package.pkl").open("rb") as handle:
        package = pickle.load(handle)
    expected_quality_names = package["metadata"]["feature_contract"]["candidate_quality_feature_names"]
    matches = {}
    scene_rows = []
    _configure_scannet200_instance_eval()
    original_load_ids = instance_eval.util_3d.load_ids
    instance_eval.util_3d.load_ids = lambda path: _class_agnostic_gt_ids(original_load_ids(path))
    try:
        for index, scene in enumerate(scenes, start=1):
            masks, original_scores, _classes, feature_rows, tracks, _candidate_audit = load_safety_scene(
                scene, args.native_cache, args.quality_ledger_root, args.track_root,
            )
            matrix, names = feature_matrix(feature_rows, FEATURE_GROUP, PROTOCOL_NAME)
            if names != expected_quality_names:
                raise ValueError(f"{scene}: quality feature schema changed after planning")
            q_model = package["quality_models"]["q"]
            q_values = canonicalize_predictions("q", q_model.predict(matrix))
            native_count = masks.shape[1]
            track_q = q_values[native_count:]
            groups, group_audit = geometry_groups_and_audit(
                masks,
                [int(row["point_count"]) for row in feature_rows[:native_count]],
                None,
            )
            group_contract = {}
            kept_native = set()
            for group_index, members in enumerate(groups):
                group_id = f"{scene}:native_geometry:{group_index:04d}"
                representative = min(
                    members, key=lambda candidate_id: (-float(original_scores[candidate_id]), candidate_id)
                )
                group_contract[group_id] = {
                    "members": [int(value) for value in members],
                    "representative": int(representative),
                }
                kept_native.add(int(representative))
            tracks = sorted(tracks, key=lambda row: int(row["track_id"]))
            track_by_id = {int(row["track_id"]): row for row in tracks}
            track_q_by_id = {
                int(track["track_id"]): float(track_q[position])
                for position, track in enumerate(tracks)
            }
            kept_tracks = set(track_by_id)
            controlled_groups, controlled_tracks = set(), set()
            for row in read_jsonl(args.plan_root / scene / "frozen_action_plan.jsonl"):
                component_groups = {str(value) for value in row["component_native_exact_geometry_group_ids"]}
                component_tracks = {int(value) for value in row["component_track_ids"]}
                if controlled_groups & component_groups or controlled_tracks & component_tracks:
                    raise ValueError(f"{scene}: plan components overlap")
                controlled_groups.update(component_groups)
                controlled_tracks.update(component_tracks)
                if not component_groups <= set(group_contract) or not component_tracks <= set(track_by_id):
                    raise ValueError(f"{scene}: plan references unknown candidates")
                kept_native.difference_update(
                    group_contract[group_id]["representative"] for group_id in component_groups
                )
                kept_native.update(
                    group_contract[str(group_id)]["representative"]
                    for group_id in row["kept_native_exact_geometry_group_ids"]
                )
                kept_tracks.difference_update(component_tracks)
                kept_tracks.update(int(value) for value in row["kept_track_ids"])

            native_ids = sorted(kept_native)
            track_ids = sorted(kept_tracks)
            track_masks = np.zeros((masks.shape[0], len(track_ids)), dtype=bool)
            for column, track_id in enumerate(track_ids):
                points, _ = _load_track_points(track_by_id[track_id], masks.shape[0])
                track_masks[points, column] = True
            selected_masks = np.concatenate([
                np.asarray(masks[:, native_ids], dtype=bool), track_masks,
            ], axis=1)
            selected_scores = np.concatenate([
                np.asarray(original_scores[native_ids], dtype=np.float64),
                np.asarray([track_q_by_id[track_id] for track_id in track_ids], dtype=np.float64),
            ])
            gt_file = str(args.gt_dir / f"{scene}.txt")
            gt, pred = instance_eval.assign_instances_for_scan(
                _prediction(selected_masks, selected_scores, len(selected_scores)), gt_file,
            )
            matches[os.path.abspath(gt_file)] = {"gt": gt, "pred": pred}
            scene_rows.append({
                "scene_name": scene,
                "kept_baseline_candidate_count": len(native_ids),
                "kept_track_candidate_count": len(track_ids),
                "selected_candidate_count": len(selected_scores),
                "geometry_group_count": len(groups),
                "canonical_mask_element_sha256": group_audit["canonical_mask_element_sha256"],
                "candidate_files_modified": False,
            })
            print(f"[frozen AP matching] {index}/60 {scene}", flush=True)
    finally:
        instance_eval.util_3d.load_ids = original_load_ids

    staging = args.output_dir.parent / f".{args.output_dir.name}.tmp.{os.getpid()}"
    if staging.exists():
        shutil.rmtree(staging)
    staging.mkdir(parents=True)
    marker = args.output_dir.parent / f".{args.output_dir.name}.ap_once_receipt.json"
    if marker.exists():
        raise ValueError(f"one-shot AP receipt already exists: {marker}")
    marker.write_text(json.dumps({
        "version": VERSION,
        "policy": POLICY,
        "ap_call_started_utc": datetime.now(timezone.utc).isoformat(),
        "ap_evaluation_run_count": 1,
        "completed": False,
        "plan_summary_sha256": audit["plan_summary_sha256"],
    }, ensure_ascii=False, indent=2, sort_keys=True) + "\n")
    try:
        # This is deliberately the sole AP aggregation call in the tool.
        selected = _evaluate(POLICY, matches, staging)
        baseline = audit["frozen_coexist_metrics"]
        summary = {
            "version": VERSION,
            "policy": POLICY,
            "experiment": "one-shot safety60 class-agnostic AP for frozen structured action plan",
            "preflight": audit,
            "frozen_coexist_baseline": baseline,
            "selected_policy_ap": selected,
            "delta_vs_frozen_coexist": {
                key: float(selected[key] - baseline[key]) for key in ("ap", "ap50", "ap25")
            },
            "scene_candidate_counts": scene_rows,
            "ground_truth_usage": "S3 AP evaluation only",
            "candidate_files_modified": False,
            "candidate_file_modification_count": 0,
            "threshold_scanning": False,
            "evaluated_policy_count": 1,
            "ap_evaluation_run_count": 1,
        }
        (staging / "summary.json").write_text(
            json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
        )
        os.replace(staging, args.output_dir)
        marker.write_text(json.dumps({
            "version": VERSION,
            "policy": POLICY,
            "ap_call_started": True,
            "ap_evaluation_run_count": 1,
            "completed": True,
            "output_summary_sha256": _sha256(args.output_dir / "summary.json"),
        }, ensure_ascii=False, indent=2, sort_keys=True) + "\n")
    except Exception:
        shutil.rmtree(staging, ignore_errors=True)
        raise
    return summary


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--official-scene-list", type=Path, required=True)
    parser.add_argument("--official-records-root", type=Path, required=True)
    parser.add_argument("--official-oof-summary", type=Path, required=True)
    parser.add_argument("--safety-scene-list", type=Path, required=True)
    parser.add_argument("--model-root", type=Path, required=True)
    parser.add_argument("--plan-root", type=Path, required=True)
    parser.add_argument("--frozen-coexist-summary", type=Path, required=True)
    parser.add_argument("--native-cache", type=Path, required=True)
    parser.add_argument("--track-root", type=Path, required=True)
    parser.add_argument("--quality-ledger-root", type=Path, required=True)
    parser.add_argument("--dataset-root", type=Path, required=True)
    parser.add_argument("--gt-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--preflight-only", action="store_true")
    parser.add_argument("--allow-gt-evaluation", action="store_true")
    args = parser.parse_args()
    for name in (
        "official_scene_list", "official_records_root", "official_oof_summary",
        "safety_scene_list", "model_root", "plan_root", "frozen_coexist_summary",
        "native_cache", "track_root", "quality_ledger_root", "dataset_root",
        "gt_dir", "output_dir",
    ):
        setattr(args, name, _resolve(getattr(args, name)))
    if args.output_dir.exists():
        raise SystemExit(f"output directory already exists; one-shot AP will not rerun: {args.output_dir}")
    audit = preflight(args)
    if args.preflight_only:
        print(json.dumps(audit, ensure_ascii=False, indent=2, sort_keys=True))
        return
    if not args.allow_gt_evaluation:
        raise SystemExit("must explicitly pass --allow-gt-evaluation after preflight")
    print(json.dumps(run_once(args, audit), ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
