#!/usr/bin/env python3
"""Run one frozen class-agnostic AP for a no-GT soft-suppression plan.

The preflight verifies scene isolation, the official100 soft-suppression
result, model and candidate-input digests, complete component coverage, and
candidate-retention invariants.  The AP aggregator is then called exactly
once for the frozen soft-suppression scores.  Candidate files are never
modified.
"""
from __future__ import annotations

import argparse
import copy
import json
import os
import pickle
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from tools.audit_train_candidate_quality_dataset import read_jsonl, read_scene_list  # noqa: E402
from tools.build_frozen_structured_soft_suppression_plan import (  # noqa: E402
    SCORE_RULE,
    VERSION as PLAN_VERSION,
)
from tools.build_safety60_structured_action_plan import POLICY, _combined_digest  # noqa: E402
from tools.build_train_candidate_component_action_utility_ledger import (  # noqa: E402
    _scene_records,
    _sha256,
)
from tools.diagnose_gvc_class_agnostic_ap import (  # noqa: E402
    _class_agnostic_gt_ids,
    _configure_scannet200_instance_eval,
    instance_eval,
)
from tools.evaluate_candidate_quality_reranking_class_agnostic_ap import (  # noqa: E402
    FEATURE_GROUP,
    PROTOCOL_NAME,
    _evaluate,
    _load_track_points,
    _prediction,
    _set_match_scores,
    _uuid_score_map,
    load_safety_scene,
)
from tools.evaluate_frozen_safety60_structured_action_plan_ap import (  # noqa: E402
    _candidate_input_paths,
)
from tools.evaluate_official100_geometry_group_ranking_oof_ap import (  # noqa: E402
    geometry_groups_and_audit,
)
from tools.train_candidate_component_action_head_oof import _metrics_from_records  # noqa: E402
from tools.train_candidate_quality_head_oof import canonicalize_predictions, feature_matrix  # noqa: E402


VERSION = "frozen_structured_soft_suppression_ap_v1"


def preflight(args: argparse.Namespace) -> dict:
    scenes = read_scene_list(args.scene_list)
    if len(scenes) != args.expected_scene_count:
        raise ValueError(f"expected {args.expected_scene_count} scenes, got {len(scenes)}")
    evaluation = set(scenes)
    overlap_counts = {}
    for path in args.disjoint_scene_list:
        overlap = sorted(evaluation & set(read_scene_list(path)))
        if overlap:
            raise ValueError(f"evaluation scenes overlap {path}: {overlap}")
        overlap_counts[str(path)] = 0

    plan_summary = json.loads((args.plan_root / "summary.json").read_text())
    required = {
        "version": PLAN_VERSION,
        "source_policy": POLICY,
        "score_rule": SCORE_RULE,
        "fitted_soft_suppression_parameter_count": 0,
        "scene_count": len(scenes),
        "feature_schema_verified": True,
        "plan_complete": True,
        "ground_truth_usage": "none",
        "candidate_files_modified": False,
        "candidate_file_modification_count": 0,
        "candidate_count_modified": False,
        "candidate_geometry_modified": False,
        "candidate_class_modified": False,
        "ap_evaluation_run": False,
        "ap_evaluation_run_count": 0,
        "threshold_scanning": False,
    }
    mismatches = {
        key: {"expected": value, "actual": plan_summary.get(key)}
        for key, value in required.items() if plan_summary.get(key) != value
    }
    if mismatches:
        raise ValueError(f"no-GT soft plan violates frozen contract: {mismatches}")

    model_metadata = json.loads((args.model_root / "metadata.json").read_text())
    package_path = args.model_root / "model_package.pkl"
    package_sha = _sha256(package_path)
    if package_sha != model_metadata["model_package_sha256"]:
        raise ValueError("model package SHA-256 mismatch")
    if plan_summary["input_provenance"]["model_package_sha256"] != package_sha:
        raise ValueError("plan was not generated by the supplied model package")
    if model_metadata.get("frozen_policy") != POLICY or model_metadata.get("threshold_scanning"):
        raise ValueError("model package is not the frozen selected-policy package")
    if model_metadata["fit_diagnostics"]["candidate_quality"]["q"]["random_seed"] != 20260808:
        raise ValueError("candidate-quality q seed differs from the frozen score contract")

    official = json.loads(args.official_soft_summary.read_text())
    if official.get("score_rule") != SCORE_RULE:
        raise ValueError("official100 soft-suppression formula differs from evaluation formula")
    delta = official.get("delta_vs_coexist", {})
    if not all(float(delta.get(name, 0.0)) > 0.0 for name in ("official_ap", "ap50", "ap25")):
        raise ValueError("official100 soft suppression is not positive on all three metrics")
    # The immutable soft-suppression report serializes each fold's soft metric,
    # while its coexist fold metrics remain in the upstream OOF result rather
    # than being duplicated here.  Require all five folds to be present; the
    # report-level all-positive delta is the frozen eligibility criterion this
    # external replay is allowed to consume.
    fold_metrics = official.get("fold_metrics", [])
    if len(fold_metrics) != 5:
        raise ValueError("official100 soft-suppression report lacks five fold metrics")
    fold_deltas = None

    aggregate = read_jsonl(args.plan_root / "soft_suppression_plan.jsonl")
    identities = {(str(row["scene_name"]), int(row["relation_component_id"])) for row in aggregate}
    if len(identities) != len(aggregate) or len(aggregate) != plan_summary["relation_component_count"]:
        raise ValueError("aggregate soft plan identities are incomplete or duplicated")
    for row in aggregate:
        factor = float(row["suppression_factor"])
        if not 0.0 <= factor <= 1.0 or row.get("candidate_retained") is not True:
            raise ValueError("soft plan violates score-factor or candidate-retention contract")

    observed_digests = {}
    for scene in scenes:
        scene_summary = json.loads((args.plan_root / scene / "summary.json").read_text())
        scene_plan = read_jsonl(args.plan_root / scene / "soft_suppression_plan.jsonl")
        if len(scene_plan) != int(scene_summary["relation_component_count"]):
            raise ValueError(f"{scene}: plan does not cover every relation component")
        digest = _combined_digest(_candidate_input_paths(scene, args))
        expected = plan_summary["input_provenance"]["scene_candidate_input_sha256"][scene]
        if digest != expected or digest != scene_summary["candidate_input_combined_sha256"]:
            raise ValueError(f"{scene}: frozen candidate-input digest mismatch")
        observed_digests[scene] = digest
    return {
        "preflight_passed": True,
        "scene_count": len(scenes),
        "disjoint_scene_overlap_counts": overlap_counts,
        "official100_soft_delta": delta,
        "official100_soft_fold_metric_count": len(fold_metrics),
        "model_package_sha256": package_sha,
        "plan_summary_sha256": _sha256(args.plan_root / "summary.json"),
        "official_soft_summary_sha256": _sha256(args.official_soft_summary),
        "candidate_input_digest_count": len(observed_digests),
        "ground_truth_read": False,
        "ap_evaluation_run_count": 0,
    }


def run_once(args: argparse.Namespace, audit: dict) -> dict:
    scenes = read_scene_list(args.scene_list)
    with (args.model_root / "model_package.pkl").open("rb") as handle:
        package = pickle.load(handle)
    expected_quality_names = package["metadata"]["feature_contract"]["candidate_quality_feature_names"]
    baseline_records = {}
    soft_records = {}
    soft_matches = {}
    score_rows = []
    scene_rows = []
    _configure_scannet200_instance_eval()
    original_load_ids = instance_eval.util_3d.load_ids
    instance_eval.util_3d.load_ids = lambda path: _class_agnostic_gt_ids(original_load_ids(path))
    try:
        for index, scene in enumerate(scenes, start=1):
            masks, native_scores, _classes, feature_rows, tracks, _candidate_audit = load_safety_scene(
                scene, args.native_cache, args.quality_ledger_root, args.track_root,
            )
            matrix, names = feature_matrix(feature_rows, FEATURE_GROUP, PROTOCOL_NAME)
            if names != expected_quality_names:
                raise ValueError(f"{scene}: quality feature schema changed after planning")
            q_model = package["quality_models"]["q"]
            q_values = canonicalize_predictions("q", q_model.predict(matrix))
            native_count = masks.shape[1]
            groups, group_audit = geometry_groups_and_audit(
                masks, [int(row["point_count"]) for row in feature_rows[:native_count]], None,
            )
            group_contract = {}
            native_ids = []
            for group_index, members in enumerate(groups):
                group_id = f"{scene}:native_geometry:{group_index:04d}"
                representative = min(
                    members, key=lambda candidate_id: (-float(native_scores[candidate_id]), candidate_id)
                )
                group_contract[group_id] = int(representative)
                native_ids.append(int(representative))
            native_ids = sorted(native_ids)

            tracks = sorted(tracks, key=lambda row: int(row["track_id"]))
            track_ids = [int(row["track_id"]) for row in tracks]
            track_by_id = {int(row["track_id"]): row for row in tracks}
            track_q = q_values[native_count:]
            track_q_by_id = {
                track_id: float(track_q[position]) for position, track_id in enumerate(track_ids)
            }
            factors = {
                **{("native", candidate_id): 1.0 for candidate_id in native_ids},
                **{("track", track_id): 1.0 for track_id in track_ids},
            }
            controlled_groups, controlled_tracks = set(), set()
            for row in read_jsonl(args.plan_root / scene / "soft_suppression_plan.jsonl"):
                component_groups = {str(value) for value in row["component_native_exact_geometry_group_ids"]}
                component_tracks = {int(value) for value in row["component_track_ids"]}
                if controlled_groups & component_groups or controlled_tracks & component_tracks:
                    raise ValueError(f"{scene}: plan components overlap")
                controlled_groups.update(component_groups)
                controlled_tracks.update(component_tracks)
                if not component_groups <= set(group_contract) or not component_tracks <= set(track_by_id):
                    raise ValueError(f"{scene}: plan references unknown candidates")
                factor = float(row["suppression_factor"])
                for group_id in row["suppressed_native_exact_geometry_group_ids"]:
                    factors[("native", group_contract[str(group_id)])] *= factor
                for track_id in row["suppressed_track_ids"]:
                    factors[("track", int(track_id))] *= factor

            track_masks = np.zeros((masks.shape[0], len(track_ids)), dtype=bool)
            for column, track_id in enumerate(track_ids):
                points, _ = _load_track_points(track_by_id[track_id], masks.shape[0])
                track_masks[points, column] = True
            combined_masks = np.concatenate([
                np.asarray(masks[:, native_ids], dtype=bool), track_masks,
            ], axis=1)
            candidate_keys = [
                *(('native', candidate_id) for candidate_id in native_ids),
                *(('track', track_id) for track_id in track_ids),
            ]
            baseline_scores = np.asarray([
                *(float(native_scores[candidate_id]) for candidate_id in native_ids),
                *(track_q_by_id[track_id] for track_id in track_ids),
            ], dtype=np.float64)
            soft_scores = np.asarray([
                baseline_scores[position] * factors[key]
                for position, key in enumerate(candidate_keys)
            ], dtype=np.float64)
            point_counts = np.count_nonzero(combined_masks, axis=0).astype(np.int64).tolist()
            gt_file = str(args.gt_dir / f"{scene}.txt")
            gt, pred = instance_eval.assign_instances_for_scan(
                _prediction(combined_masks, baseline_scores, len(baseline_scores)), gt_file,
            )
            baseline_cache = {"gt": gt, "pred": pred, "uuid_by_candidate": {}}
            baseline_uuid_scores = _uuid_score_map(pred, baseline_scores, point_counts)
            included_positions = [i for i, count in enumerate(point_counts) if count >= 100]
            included_uuids = [row["uuid"] for row in pred["chair"]]
            if len(included_positions) != len(included_uuids):
                raise ValueError(f"{scene}: evaluator candidate acceptance mismatch")
            baseline_cache["uuid_by_candidate"] = {
                candidate_keys[position]: uuid
                for position, uuid in zip(included_positions, included_uuids)
            }
            baseline_records[scene] = _scene_records(
                baseline_cache, set(native_ids), set(track_ids)
            )

            soft_gt = copy.deepcopy(gt)
            soft_pred = copy.deepcopy(pred)
            soft_uuid_scores = _uuid_score_map(pred, soft_scores, point_counts)
            match_key = os.path.abspath(gt_file)
            soft_matches[match_key] = {"gt": soft_gt, "pred": soft_pred}
            _set_match_scores({match_key: soft_matches[match_key]}, soft_uuid_scores)
            soft_cache = {
                "gt": soft_gt,
                "pred": soft_pred,
                "uuid_by_candidate": baseline_cache["uuid_by_candidate"],
            }
            soft_records[scene] = _scene_records(soft_cache, set(native_ids), set(track_ids))

            for position, key in enumerate(candidate_keys):
                score_rows.append({
                    "scene_name": scene,
                    "candidate_kind": key[0],
                    "candidate_id": key[1],
                    "original_score": float(baseline_scores[position]),
                    "suppression_factor": float(factors[key]),
                    "selected_score": float(soft_scores[position]),
                    "candidate_retained": True,
                })
            scene_rows.append({
                "scene_name": scene,
                "native_geometry_representative_count": len(native_ids),
                "track_candidate_count": len(track_ids),
                "candidate_count": len(candidate_keys),
                "score_changed_candidate_count": sum(factors[key] < 1.0 for key in candidate_keys),
                "canonical_mask_element_sha256": group_audit["canonical_mask_element_sha256"],
                "candidate_files_modified": False,
            })
            print(f"[frozen soft AP matching] {index}/{len(scenes)} {scene}", flush=True)
    finally:
        instance_eval.util_3d.load_ids = original_load_ids

    baseline_metrics = _metrics_from_records(baseline_records)
    soft_record_metrics = _metrics_from_records(soft_records)
    staging = args.output_dir.parent / f".{args.output_dir.name}.tmp.{os.getpid()}"
    if staging.exists():
        shutil.rmtree(staging)
    staging.mkdir(parents=True)
    marker = args.output_dir.parent / f".{args.output_dir.name}.ap_once_receipt.json"
    if marker.exists():
        raise ValueError(f"one-shot AP receipt already exists: {marker}")
    marker.write_text(json.dumps({
        "version": VERSION,
        "source_policy": POLICY,
        "score_rule": SCORE_RULE,
        "ap_call_started_utc": datetime.now(timezone.utc).isoformat(),
        "ap_evaluation_run_count": 1,
        "completed": False,
        "plan_summary_sha256": audit["plan_summary_sha256"],
    }, ensure_ascii=False, indent=2, sort_keys=True) + "\n")
    try:
        selected = _evaluate("soft_suppression", soft_matches, staging)
        record_selected = {
            "ap": soft_record_metrics["official_ap"],
            "ap50": soft_record_metrics["threshold_metrics"]["50"]["ap"],
            "ap25": soft_record_metrics["threshold_metrics"]["25"]["ap"],
        }
        errors = {key: float(selected[key] - record_selected[key]) for key in selected}
        if any(abs(value) > 1e-10 for value in errors.values()):
            raise ValueError(f"record metrics differ from the sole AP aggregation call: {errors}")
        baseline = {
            "ap": baseline_metrics["official_ap"],
            "ap50": baseline_metrics["threshold_metrics"]["50"]["ap"],
            "ap25": baseline_metrics["threshold_metrics"]["25"]["ap"],
        }
        summary = {
            "version": VERSION,
            "source_policy": POLICY,
            "score_rule": SCORE_RULE,
            "experiment": "one-shot frozen robustness AP for structured soft suppression",
            "preflight": audit,
            "frozen_coexist_baseline": baseline,
            "soft_suppression_ap": selected,
            "delta_vs_frozen_coexist": {
                key: float(selected[key] - baseline[key]) for key in ("ap", "ap50", "ap25")
            },
            "scene_candidate_counts": scene_rows,
            "score_changed_candidate_count": sum(
                int(row["score_changed_candidate_count"]) for row in scene_rows
            ),
            "candidate_count_modified": False,
            "candidate_geometry_modified": False,
            "candidate_class_modified": False,
            "candidate_files_modified": False,
            "candidate_file_modification_count": 0,
            "ground_truth_usage": "one frozen AP evaluation only",
            "threshold_scanning": False,
            "evaluated_policy_count": 1,
            "ap_evaluation_run_count": 1,
        }
        (staging / "candidate_scores.jsonl").write_text("".join(
            json.dumps(row, ensure_ascii=False, sort_keys=True) + "\n" for row in score_rows
        ))
        (staging / "summary.json").write_text(
            json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
        )
        os.replace(staging, args.output_dir)
        marker.write_text(json.dumps({
            "version": VERSION,
            "ap_call_started": True,
            "ap_evaluation_run_count": 1,
            "completed": True,
            "output_summary_sha256": _sha256(args.output_dir / "summary.json"),
        }, ensure_ascii=False, indent=2, sort_keys=True) + "\n")
    except Exception:
        shutil.rmtree(staging, ignore_errors=True)
        raise
    return summary


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--scene-list", type=Path, required=True)
    parser.add_argument("--expected-scene-count", type=int, required=True)
    parser.add_argument("--disjoint-scene-list", type=Path, action="append", default=[])
    parser.add_argument("--official-soft-summary", type=Path, required=True)
    parser.add_argument("--model-root", type=Path, required=True)
    parser.add_argument("--plan-root", type=Path, required=True)
    parser.add_argument("--native-cache", type=Path, required=True)
    parser.add_argument("--track-root", type=Path, required=True)
    parser.add_argument("--quality-ledger-root", type=Path, required=True)
    parser.add_argument("--dataset-root", type=Path, required=True)
    parser.add_argument("--gt-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--preflight-only", action="store_true")
    parser.add_argument("--allow-gt-evaluation", action="store_true")
    args = parser.parse_args()
    for name in (
        "scene_list", "official_soft_summary", "model_root", "plan_root", "native_cache",
        "track_root", "quality_ledger_root", "dataset_root", "gt_dir", "output_dir",
    ):
        path = getattr(args, name)
        setattr(args, name, path if path.is_absolute() else PROJECT_ROOT / path)
    args.disjoint_scene_list = [
        path if path.is_absolute() else PROJECT_ROOT / path for path in args.disjoint_scene_list
    ]
    if args.output_dir.exists():
        raise SystemExit(f"output directory already exists; one-shot AP will not rerun: {args.output_dir}")
    audit = preflight(args)
    if args.preflight_only:
        print(json.dumps(audit, ensure_ascii=False, indent=2, sort_keys=True))
        return
    if not args.allow_gt_evaluation:
        raise SystemExit("must explicitly pass --allow-gt-evaluation after preflight")
    print(json.dumps(run_once(args, audit), ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
